### ISSUE TITLE
Injecting functions

### ISSUE THREAD

**Issue by frekw** [facebookgo/inject#10]
Hi!

Is there any plans to allow injection of function types? The use case is a pretty standard factory setup; the need to delay the actual creation of a struct until runtime.

An example:

```
type Create func() string

type Something struct {
  CreateFn Create `inject:""`
}
```

the solution is to wrap `Create` into an interface, and have multiple dummy structs implement the interface and inject those instead, but that seems like more boilerplate than should be needed.

Or maybe I'm missing something?

**Comment by daaku** [comment]
Haven't thought about it much, but my initial reaction is that I'd like to avoid adding more complexity. I already regret named inject and map initialization support.
