### ISSUE TITLE
What's with the license?

### ISSUE THREAD

**Issue by bradleypeabody** [facebookgo/inject#14]
Any chance this can be released under something like MIT or Apache or something without that funky patent clause in it?

Regardless of arguments for/against that clause, are you sure that company policy requires it to be used in this case?  It's a pretty small project and not something of core importance to FB or likely to have any monetary value.  That license seems a bit overkill, if not generally, at least in this case for this project.

**Comment by fantasist** [comment]
It's probably forgotten with the shutdown of Parse. I don't see any issue with updating it to MIT license like React. I'm going to post internally and find out how to convert the license of all projects under facebookgo.

**Comment by fantasist** [comment]
Updated the license.
