### ISSUE TITLE
Populate/Provide returns err

### ISSUE THREAD

**Issue by kdeenanauth** [facebookgo/inject#8]
Hello,

I've been using enjoying using inject in my projects. Thank you for open sourcing this library!

I've found one inconsistency that doesn't seem 'go-like' is that `object.Populate`, `graph.Provide`, and `graph.Populate` all return `err` without panicking. I feel that all of the errors that are passed back are not recoverable errors and require the developer to change their usage of library. Failing to check for the error leaves the graph in a bad state, but checking for errors is also somewhat onerous.

Rather than change the behavior, and break backwards compatibility, I would suggest adding a `MustProvide` and `MustPopulate` that would panic immediately upon receiving an error. I would be happy to submit a patch if you believe it's a good idea, as I've wrapped the functionality already.

Cheers,
Kevin

**Comment by daaku** [comment]
IMO returning errors is in fact a very go thing to do :)

Internally when we use `inject` all our usage is via another package that wraps inject (provides some standard things like loggers, invokes startstop and so on). If you have something like this, it's a good place to put the logic you're suggesting. Also it's trivial to have a method like such:

```go
func must(err error) {
  if err != nil {
    panic(err)
  }
}
```

Which you can then use like `must(graph.Provide(...))` to achieve the same effect.
